### ISSUE TITLE
Query on a ObjectId that is stored as string in object

### ISSUE THREAD

**Issue by brianoneil** [craiggwilson/fluent-mongo#8] opened 2011-06-02 04:50 UTC
I am trying to query an object that is referenced by another object by the document id.  My query is as follows

```
     var devices = from device in devicecollection.AsQueryable()
                      where device.shootid == shootid
                      select device;
```

The device.shootid is of type string, but it is stored as an ObjectId in MongoDB (see snippet from class below) and represents a referenced document.

```
    public string devicename { get; set; }
    public string incomingpath { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string shootid { get; set; }
```

if I write the query with the driver like this it works.

```
    var query = Query.EQ("shootid", ObjectId.Parse(shootid));
    var devices = devicecollection.Find(query);
```

How can I represent this using the Linq provider?

**Comment by craiggwilson** [comment] 2011-06-02 11:57
Well, the issue is that the linq provider is just passing the code down to driver and the driver isn't doing anything with it.  In other words, the linq provider is constructing the query as Query.EQ("shootid", shootid).  The driver already knows that you want "shootid" to be persisted as an ObjectId, so it should handle the conversion.  I'd like to see what the 10gen guys (Robert) say about this as I personally believe this should be a native experience.  If they don't want to do it, I'll see what we can do on our side.

So, can you ask on the mongodb user group about them getting this fixed (handled)?

**Comment by brianoneil** [comment] 2011-06-02 21:13
Yeah, I have talked to Robert before...  I will ask him the question and see what we can come up with on it.  Thanks for the quick response.

**Comment by brianoneil** [comment] 2011-06-02 22:05
okay, talked to Robert and he thinks that it should be handled at the linq layer since you already know the object type and the query builder doesn't have the necessary information (when building the query) to adjust the output of the query.

I can see both sides of the argument of who should handle it, but I don't think he want to do it in the driver.  It would be great if you would handle the mappings (another scenario that I thought of when talking with Robert) and BsonRepresentation information that has been applied to the class definition.  

thanks for your help on this...

-Brian

**Comment by craiggwilson** [comment] 2011-06-02 22:25
Yeah, I posted to the user board after I responded this morning.  We have an ongoing discussion where I believe the driver should be doing this stuff.  Anyways...

As far as the linq provider, the name of the property is already being handled.  What is failing is the mapping of the type to your BsonRepresentation.  I can definitely handle this (I think), but it will require some work because I'm not tracking the BsonMemberMap all the way through.  So, I'll just need to work it out.

**Comment by brianoneil** [comment] 2011-09-03 20:58
Any chance you have looked at this?  I would love to be able to use linq with Mongo but most of our documents use strings as the document ID because we are using data services on top of the mongo data and it is just a better experience to consume the _id as a string.

Thanks,

-Brian

**Comment by craiggwilson** [comment] 2011-09-03 21:21
I haven't had a chance.  I'll get to it at some point because this is a big deal...  I need it for my stuff as well, just not yet.  If you need it sooner rather than later, please feel free to jump in.

**Comment by gabrielduford** [comment] 2011-09-14 14:31
Just got this problem too while starting a new project.

**Comment by craiggwilson** [comment] 2011-09-20 09:41
nekresh submitted a pull request that I merged in.  It might have fixed this issue.  Please pull the latest FluentMongo from nuget, 1.2, and see if this issue is resolved.

**Comment by nekresh** [comment] 2011-09-28 08:54
I was aiming specifically to fix this issue in my pull request.
There should be unit tests validating this case.

**Closed as completed** 2011-11-22 13:23 UTC
