### ISSUE TITLE
Deferring More than one Where() clause in a query.

### ISSUE THREAD

**Issue by PhoenixWebGroupJay** [craiggwilson/fluent-mongo#6] opened 2011-04-28 22:28 UTC
When I run the following code:

```
        var settlement = _DailySettlements
            .Where(d => d.Type == SettlementType.Option)
            .Select(d => d as OptionSettlement)
            .Where(d => d.MarketProductId == option.MarketProductId)
            .Where(d => d.Strike == option.Strike)
            .Where(d => d.Contract.Month == option.Contract.Month)
            .Where(d => d.Contract.Month == option.Contract.Month)
            .Where(d => d.CallOrPut == option.CallOrPut);
```

I expect an enumerable containing the items from the collection that match that criteria. But Instead, I receive an error:

```
QueryFailure flag set: $where compile error (response: { "$err" : "$where compile error", "code" : 10070 })
```

I achieve the expected results by pulling the collection into memory with a ToList() command, but this is less than ideal.  Just curious if there's a way to avoid having to do the following:

```
        var settlement = _DailySettlements
            .Where(d => d.Type == SettlementType.Option)
            .Select(d => d as OptionSettlement)
            .ToList()
            .Where(d => d.MarketProductId == option.MarketProductId)
            .Where(d => d.Strike == option.Strike)
            .Where(d => d.Contract.Month == option.Contract.Month)
            .Where(d => d.Contract.Month == option.Contract.Month)
            .Where(d => d.CallOrPut == option.CallOrPut);
```

**Comment by craiggwilson** [comment] 2011-04-28 23:36
The problem is your select line.  Unfortunately, there isn't a way to translate an "as" operation into a server side query.  I'm not sure how I would go about handling this. 

If you could write a test demonstrating the issue, I'll see if I can figure something out.

**Comment by nekresh** [comment] 2011-08-16 12:51
The `as` should just be a projection as the driver will normally take care of using the correct class from the data.
On the database part, there is no need to translate the `as`, mongo can take care of a query referencing fields that aren't present on every records. So the query will just have the others fields in it's body.

However, I do prefer using `OfType<T>()` instead of using a `select` with `as` as `OfType<T>()` will constraint the records on the discriminator of the type whereas `select` with `as` won't garantee that the records will be of the correct type.

I've issed a pull request for this case https://github.com/craiggwilson/fluent-mongo/pull/21

**Comment by craiggwilson** [comment] 2011-08-20 22:02
Please try the latest.  I have merged in nekresh's commits so it might have fixed your issue.

**Closed as completed** 2011-11-22 13:30 UTC
